eCommerce.Web/eCommerce.Web/Controllers/CartController.cs
using eCommerce.Data;
using eCommerce.Entity.Enumeratinos;
using eCommerce.Entity.Models;
using eCommerce.Service.Interfaces;
using eCommerce.Web.Utils.Config;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;

namespace eCommerce.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ILogger<CartController> _logger;
        private readonly IUserService _userService;

        public CartController(ILogger<CartController> logger, AppDbContext context, IUserService userService)
        {
            _logger = logger;
            _context = context;
            _userService = userService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {

            foreach (var item in Config.CartList)
            {
                var product = _context.Products.FirstOrDefault(x => x.Id == item.Id);
                if (product != null)
                {
                    if (!string.IsNullOrEmpty(product.ImageUrl))
                        item.ImageUrl = product.ImageUrl;
                }

            }
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Cart[] cartList)
        {
            var user = _context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);

            if (cartList.Length > 0)
            {
                var order = new Order();
                order.UserId = user.Id;
                order.CreatedDate = DateTime.Now;
                order.Status = OrderStatus.Pending;

                order.OrderDetails = cartList.Select(x => new OrderDetail
                {
                    ProductId=x.Id,
                    Quantity=x.Quantity,
                    Price=x.Price
                }).ToList();

                _context.Orders.Add(order);
                _context.SaveChanges();

                Config.CartList.Clear();

                _userService.SendEmail(user);


            }

            return RedirectToAction("Index");
        }
    }
}

eCommerce.Web/eCommerce.Web/Views/Cart/Index.cshtml
@using eCommerce.Web.Utils.Config
@using eCommerce.Data.Utils.PartialPermissions
<div class="container">
    <form asp-action="Checkout" asp-controller="Cart">
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description"></td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>


                    @for (int i = 0; i < Config.CartList.Count(); i++)
                    {

                        var item = Config.CartList.ElementAt(i);
                        <tr>
                            <td class="cart_product">
                                <input type="hidden" name="cartList[@i].Id" value="@item.Id" />
                                <input type="hidden" name="cartList[@i].Name" value="@item.Name" />
                                <input type="hidden" name="cartList[@i].Quantity" value="@item.Quantity" />
                                <input type="hidden" name="cartList[@i].Price" value="@item.Price" />

                                <a href=""><img style="width:70px;" src="~/@item.ImageUrl" alt=""></a>
                            </td>
                            <td class="cart_description">
                                <h4><a href="">@item.Name</a></h4>
                            </td>
                            <td class="cart_price">
                                <p>@item.Price</p>
                            </td>
                            <td class="cart_quantity">

                                <div class="cart_quantity_button">
                                    <a class="cart_quantity_up" @*@(item.Quantity++)*@>+ </a>
                                    <input class="cart_quantity_input" type="text" name="quantity" value="@(item.Quantity)" autocomplete="om" size="2">
                                    <a class="cart_quantity_down" href="" >- </a>
                                </div>
                            </td>
                            <td class="cart_total">
                                <p class="cart_total_price">@(item.Price*item.Quantity)</p>
                            </td>

                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href="@Url.Action("Delete", "Category", new { id=item.Id})"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>





                    }


                </tbody>
            </table>
            @if ((await AuthorizationService.AuthorizeAsync(User, Permissions.Checkout.View)).Succeeded)
            {
                <div class="col-sm-6">
                    <div class="total_area">

                        <button type="submit" class="btn btn-default check_out" href="">Check Out</button>
                    </div>
                </div>
            }

        </div>


    </form>
  
</div>